version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_PATH=./database/farmalert.db
      - JWT_SECRET=farmalert-ia-super-secret-jwt-key-2024-production
      - JWT_EXPIRES_IN=7d
      - OPENWEATHER_API_KEY=216cc64624e339d6f32a6a4c859696b1
      - OPENWEATHER_BASE_URL=https://api.openweathermap.org/data/2.5
      - CORS_ORIGIN=http://localhost:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOG_LEVEL=info
      - LOG_FILE=./logs/app.log
    volumes:
      - ./server/database:/app/database
      - ./server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: farmalert-network